# Generated by Django 5.1.2 on 2024-10-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('send_private_email', 'can send private email')]},
        ),
    ]
